---
name: actionmailer
version: '7.0'
source:
  type: git
  name: ruby/gem_rbs_collection
  revision: cf8621efa730a5af697634797b00e6976b3ffaeb
  remote: https://github.com/ruby/gem_rbs_collection.git
  repo_dir: gems
